### ISSUE TITLE
Reply Error: MOVED

### ISSUE THREAD

**Issue by lightninglu10** [NodeRedis/node-redis-parser#39]
Hey guys, I'm trying to connect to redis using superlogin https://github.com/colinskow/superlogin/blob/ebd34450895e24e5f6ed81a5c23802c18da6786d/config.example.js

and they're using your package. I have a cluster setup on AWS and not a single host and when I try to connect, I get the error below:

```
{ ReplyError: MOVED 449 172.31.29.70:6379
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:303:14)
  command: 'PSETEX',
```

Is this repo setup for clustering?

**Comment by BridgeAR** [comment]
Right now you have to use a third party module to use cluster. E.g. https://github.com/gosquared/redis-clustr

**Comment by jose920405** [comment]
> Right now you have to use a third party module to use cluster. E.g. https://github.com/gosquared/redis-clustr

This still happening after I move to `redis-clustr`.
