### ISSUE TITLE
Publish 3.0.0?

### ISSUE THREAD

**Issue by guidobouman** [NodeRedis/node-redis-parser#41]
Shouldn't 3.0.0 be published as a release so `node-redis` can use this update? (Finally fixing the `can't find module hiredis` error when using webpack)

**Comment by Salakar** [comment]
This was published to NPM over a year ago so not sure what you guys are on about 😀 

![image](https://user-images.githubusercontent.com/5347038/39230345-1f2af8dc-485e-11e8-9d0a-b84c6840c848.png)

Will close this issue. If there's a specific issue that's not been addressed in the v3.0.0 release then feel free to raise a separate issue for it

**Comment by guidobouman** [comment]
Ah, I didn't see it in the releases here on GitHub: https://github.com/NodeRedis/node-redis-parser/releases. Oopsies.

**Comment by luin** [comment]
And also there's not a git tag for v3 😆
