### ISSUE TITLE
Socket.io adapter emitted error event: { ParserError: Protocol error, got "a" as reply type byte. Please report this.

### ISSUE THREAD

**Issue by danil-z** [NodeRedis/node-redis-parser#46]
verbo: Socket.io adapter emitted error event: { ParserError: Protocol error, got "a" as reply type byte. Please report this.
    at parseType (/app/node_modules/redis-parser/lib/parser.js:305:34)
    at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:563:20)
    at Socket.<anonymous> (/app/node_modules/machinepack-redis/node_modules/redis/index.js:267:27)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
  offset: 138,
  buffer: '{"type":"Buffer","data":[43,79,75,13,10,36,50,49,49,57,13,10,35,32,83,101,114,118,101,114,13,10,114,101,100,105,115,95,118,101,114,115,105,111,110,58,50,46,56,46,50,52,13,10,114,101,100,105,115,95,103,105,116,95,115,104,97,49,58,100,99,101,55,102,55,53,54,13,10,114,101,100,105,115,95,103,105,116,95,100,105,114,116,121,58,48,13,10,114,101,100,105,115,95,98,117,105,108,100,95,105,100,58,52,97,51,53,48,48,55,52,101,98,52,52,100,53,52,100,13,10,114,101,100,105,115,95,109,111,100,101,58,115,116,97,110,100,97,108,111,110,101,13,10,111,115,58,76,105,110,117,120,32,52,46,49,53,46,49,53,45,51,50,46,101,108,54,112,105,101,32,120,56,54,95,54,52,13,10,97,114,99,104,95,98,105,116,115,58,54,52,13,10,109,117,108,116,105,112,108,101,120,105,110,103,95,97,112,105,58,101,112,111,108,108,13,10,103,99,99,95,118,101,114,115,105,111,110,58,52,46,56,46,52,13,10,112,114,111,99,101,115,115,95,105,100,58,50,48,13,10,114,117,110,95,105,100,58,50,50,102,53,52,48,53,55,101,55,51,56,102,51,49,48,49,100,53,56,52,57,100,97,57,50,48,51,55,97,55,57,101,55,98,56,52,56,98,48,13,10,116,99,112,95,112,111,114,116,58,51,49,57,57,50,13,10,117,112,116,105,109,101,95,105,110,95,115,101,99,111,110,100,115,58,50,52,52,48,51,56,55,13,10,117,112,116,105,109,101,95,105,110,95,100,97,121,115,58,50,56,13,10,104,122,58,49,48,13,10,108,114,117,95,99,108,111,99,107,58,49,54,53,54,57,49,54,49,13,10,99,111,110,102,105,103,95,102,105,108,101,58,47,97,112,112,47,114,101,100,105,115,46,99,111,110,102,13,10,13,10,35,32,67,108,105,101,110,116,115,13,10,99,111,110,110,101,99,116,101,100,95,99,108,105,101,110,116,115,58,49,49,13,10,99,108,105,101,110,116,95,108,111,110,103,101,115,116,95,111,117,116,112,117,116,95,108,105,115,116,58,48,13,10,99,108,105,101,110,116,95,98,105,103,103,101,115,116,95,105,110,112,117,116,95,98,117,102,58,48,13,10,98,108,111,99,107,101,100,95,99,108,105,101,110,116,115,58,48,13,10,13,10,35,32,77,101,109,111,114,121,13,10,117,115,101,100,95,109,101,109,111,114,121,58,49,51,48,57,49,53,50,56,13,10,117,115,101,100,95,109,101,109,111,114,121,95,104,117,109,97,110,58,49,50,46,52,57,77,13,10,117,115,101,100,95,109,101,109,111,114,121,95,114,115,115,58,51,49,57,53,50,56,57,54,13,10,117,115,101,100,95,109,101,109,111,114,121,95,112,101,97,107,58,52,54,57,57,57,51,49,50,13,10,117,115,101,100,95,109,101,109,111,114,121,95,112,101,97,107,95,104,117,109,97,110,58,52,52,46,56,50,77,13,10,117,115,101,100,95,109,101,109,111,114,121,95,108,117,97,58,51,54,56,54,52,13,10,109,101,109,95,102,114,97,103,109,101,110,116,97,116,105,111,110,95,114,97,116,105,111,58,50,46,52,52,13,10,109,101,109,95,97,108,108,111,99,97,116,111,114,58,106,101,109,97,108,108,111,99,45,51,46,54,46,48,13,10,13,10,35,32,80,101,114,115,105,115,116,101,110,99,101,13,10,108,111,97,100,105,110,103,58,48,13,10,114,100,98,95,99,104,97,110,103,101,115,95,115,105,110,99,101,95,108,97,115,116,95,115,97,118,101,58,54,51,13,10,114,100,98,95,98,103,115,97,118,101,95,105,110,95,112,114,111,103,114,101,115,115,58,48,13,10,114,100,98,95,108,97,115,116,95,115,97,118,101,95,116,105,109,101,58,49,53,50,54,53,49,56,52,57,51,13,10,114,100,98,95,108,97,115,116,95,98,103,115,97,118,101,95,115,116,97,116,117,115,58,111,107,13,10,114,100,98,95,108,97,115,116,95,98,103,115,97,118,101,95,116,105,109,101,95,115,101,99,58,48,13,10,114,100,98,95,99,117,114,114,101,110,116,95,98,103,115,97,118,101,95,116,105,109,101,95,115,101,99,58,45,49,13,10,97,111,102,95,101,110,97,98,108,101,100,58,48,13,10,97,111,102,95,114,101,119,114,105,116,101,95,105,110,95,112,114,111,103,114,101,115,115,58,48,13,10,97,111,102,95,114,101,119,114,105,116,101,95,115,99,104,101,100,117,108,101,100,58,48,13,10,97,111,102,95,108,97,115,116,95,114,101,119,114,105,116,101,95,116,105,109,101,95,115,101,99,58,45,49,13,10,97,111,102,95,99,117,114,114,101,110,116,95,114,101,119,114,105,116,101,95,116,105,109,101,95,115,101,99,58,45,49,13,10,97,111,102,95,108,97,115,116,95,98,103,114,101,119,114,105,116,101,95,115,116,97,116,117,115,58,111,107,13,10,97,111,102,95,108,97,115,116,95,119,114,105,116,101,95,115,116,97,116,117,115,58,111,107,13,10,13,10,35,32,83,116,97,116,115,13,10,116,111,116,97,108,95,99,111,110,110,101,99,116,105,111,110,115,95,114,101,99,101,105,118,101,100,58,50,52,52,51,55,51,13,10,116,111,116,97,108,95,99,111,109,109,97,110,100,115,95,112,114,111,99,101,115,115,101,100,58,50,51,52,57,55,48,54,55,13,10,105,110,115,116,97,110,116,97,110,101,111,117,115,95,111,112,115,95,112,101,114,95,115,101,99,58,49,13,10,116,111,116,97,108,95,110,101,116,95,105,110,112,117,116,95,98,121,116,101,115,58,52,51,56,48,56,54,49,52,56,54,13,10,116,111,116,97,108,95,110,101,116,95,111,117,116,112,117,116,95,98,121,116,101,115,58,49,50,57,53,54,52,51,51,57,57,53,13,10,105,110,115,116,97,110,116,97,110,101,111,117,115,95,105,110,112,117,116,95,107,98,112,115,58,48,46,48,53,13,10,105,110,115,116,97,110,116,97,110,101,111,117,115,95,111,117,116,112,117,116,95,107,98,112,115,58,48,46,48,50,13,10,114,101,106,101,99,116,101,100,95,99,111,110,110,101,99,116,105,111,110,115,58,48,13,10,115,121,110,99,95,102,117,108,108,58,51,13,10,115,121,110,99,95,112,97,114,116,105,97,108,95,111,107,58,48,13,10,115,121,110,99,95,112,97,114,116,105,97,108,95,101,114,114,58,48,13,10,101,120,112,105,114,101,100,95,107,101,121,115,58,49,48,52,49,48,49,54,13,10,101,118,105,99,116,101,100,95,107,101,121,115,58,48,13,10,107,101,121,115,112,97,99,101,95,104,105,116,115,58,49,51,50,51,48,13,10,107,101,121,115,112,97,99,101,95,109,105,115,115,101,115,58,48,13,10,112,117,98,115,117,98,95,99,104,97,110,110,101,108,115,58,51,13,10,112,117,98,115,117,98,95,112,97,116,116,101,114,110,115,58,49,13,10,108,97,116,101,115,116,95,102,111,114,107,95,117,115,101,99,58,49,48,56,52,13,10,13,10,35,32,82,101,112,108,105,99,97,116,105,111,110,13,10,114,111,108,101,58,109,97,115,116,101,114,13,10,99,111,110,110,101,99,116,101,100,95,115,108,97,118,101,115,58,50,13,10,115,108,97,118,101,48,58,105,112,61,49,55,46,49,50,49,46,49,51,56,46,49,53,56,44,112,111,114,116,61,51,49,48,49,49,44,115,116,97,116,101,61,111,110,108,105,110,101,44,111,102,102,115,101,116,61,52,49,55,50,48,56,49,49,52,52,44,108,97,103,61,49,13,10,115,108,97,118,101,49,58,105,112,61,49,55,46,49,50,49,46,49,52,56,46,56,54,44,112,111,114,116,61,51,49,48,48,55,44,115,116,97,116,101,61,111,110,108,105,110,101,44,111,102,102,115,101,116,61,52,49,55,50,48,56,49,49,52,52,44,108,97,103,61,49,13,10,109,97,115,116,101,114,95,114,101,112,108,95,111,102,102,115,101,116,58,52,49,55,50,48,56,49,49,52,52,13,10,114,101,112,108,95,98,97,99,107,108,111,103,95,97,99,116,105,118,101,58,49,13,10,114,101,112,108,95,98,97,99,107,108,111,103,95,115,105,122,101,58,49,48,52,56,53,55,54,13,10,114,101,112,108,95,98,97,99,107,108,111,103,95,102,105,114,115,116,95,98,121,116,101,95,111,102,102,115,101,116,58,52,49,55,49,48,51,50,53,54,57,13,10,114,101,112,108,95,98,97,99,107,108,111,103,95,104,105,115,116,108,101,110,58,49,48,52,56,53,55,54,13,10,13,10,35,32,67,80,85,13,10,117,115,101,100,95,99,112,117,95,115,121,115,58,50,48,51,49,46,56,50,13,10,117,115,101,100,95,99,112,117,95,117,115,101,114,58,49,49,56,54,46,51,49,13,10,117,115,101,100,95,99,112,117,95,115,121,115,95,99,104,105,108,100,114,101,110,58,55,55,46,50,50,13,10,117,115,101,100,95,99,112,117,95,117,115,101,114,95,99,104,105,108,100,114,101,110,58,54,49,54,46,53,51,13,10,13,10,35,32,75,101,121,115,112,97,99,101,13,10,100,98,48,58,107,101,121,115,61,51,52,54,56,49,44,101,120,112,105,114,101,115,61,51,52,54,56,49,44,97,118,103,95,116,116,108,61,52,52,48,48,56,50,56,51,13,10,13,10]}' }

redis: 2.6.3
redis-parser 2.6.0

**Comment by BridgeAR** [comment]
I just had a look at this and I doubt that the parser made a mistake.

Can you please tell me how exactly it came to this error and are you by any chance able to reproduce this?

**Comment by BridgeAR** [comment]
I am closing this as there has never been a follow-up. Please comment if something like this happens again / if there is any new information about it.
