### ISSUE TITLE
Large array lengths can cause an unhandled RangeError

### ISSUE THREAD

**Issue by ghost** [NodeRedis/node-redis-parser#47]
I'm seeing an unhandled exception in cases where the parser is given invalid data that happens to contain something that looks like an array. Part of the problem is that the parser will preallocate an array using whatever length parameter was given (valid or not) as seen [here](https://github.com/NodeRedis/node-redis-parser/blob/5c76401c02fe6d8e166fab855ae6768192ecdf4f/lib/parser.js#L212). If length happens to be a very large positive number, then this will result in a RangeError being thrown.

You can test this by having the parser read this buffer: `Buffer.from("2AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0D0A", "hex")`. Add more bytes and length will eventually go to Infinity.

Something should be done to at least handle the potential exception and treat it as a parsing error.

**Comment by BridgeAR** [comment]
@nkochakian are you using the parser directly in some way? Redis should always only return valid array length. As to [RESP](https://redis.io/topics/protocol) it will only reach that function in case it is told that the next data is going to be an array with that specific length. So e.g. `*99999999999999\r\n[actual super long data]\n\n`. But that is just plain out of range for JS.

**Comment by nkochakian** [comment]
Yes, it is currently being used as a communication method with a server that passes bytes from TCP sockets directly to the parser. I understand that this wasn't the intended use for the parser, and a Redis server shouldn't intentionally return invalid data, but I was expecting the parser to handle malformed input a little more gracefully.

**Comment by BridgeAR** [comment]
One problem about handling error differently is that the parser would not know what to do. It could theoretically verify the input and emit an error in case of malformed input but that would a) increase the complexity b) reduce the performance and c) it has no benefit over just wrapping the call itself in a try catch.
