### ISSUE TITLE
RedisError is undefined

### ISSUE THREAD

**Issue by guimard** [NodeRedis/node-redis-parser#49]
Hello,

in redis tests (`lib/customErrors.js` line 5), this value is undefined:
```
var RedisError = require('redis-parser').RedisError;
```
It seems that RedisError isn't inherited from redis-errors. So I'm unable to launch tests.

Cheers,
Xavier

**Comment by guimard** [comment]
Fixed using redis-parser < 3

**Comment by BridgeAR** [comment]
They are not exported by the parser anymore and were moved out in a separate package instead (`redis-errors`).
