### ISSUE TITLE
hiredis is not compiling in nodejs 12

### ISSUE THREAD

**Issue by rj-david** [NodeRedis/node-redis-parser#53]
Is there any way that this package will no longer depend on hiredis? Hiredis is not building properly using node-gyp in nodejs 12

**Comment by stelabrego** [comment]
I'm getting the same issue when building with parcel

**Comment by sookoll** [comment]
Any news on this? As hiredis is pretty much abonded, it should be removed as dependency.

**Comment by swateek** [comment]
@sookoll could you install "redis"? I didn't quite understand your solution. Help?

**Comment by yosiat** [comment]
If you can upgrade the latest node-redis you don't need hiredis, it uses this repo which is fastest than hiredis as authors claim.

If you are like me and stuck at some version, you can use this fork https://github.com/redis/hiredis-node/pull/144 until the PR will get merged

**Comment by swateek** [comment]
I really didn't need hiredis. I moved to use "ioredis" and it works good for me.

**Comment by Salakar** [comment]
Hey all,

`hiredis` is no longer used in the latest parser, the the `redis` library has been updated to the latest parser version in https://github.com/NodeRedis/node_redis/commit/78936ac50c43ceb74654501a5da4b2994efe1217 (unreleased still, no eta).

Given that a fix is sat on master for this I'm going to go ahead and close this issue now. Thanks

**Comment by fedealconada** [comment]
I'm having this issue when trying to install `redis-connect`.... any clue @Salakar ?

**Comment by ropre4** [comment]
It's been more than a year, can there be a new release to include this fix? redis-parser, and redis packages do not work on node 12 and node 14.
