### ISSUE TITLE
Very critical bug in javascript parser 2.0.0+

### ISSUE THREAD

**Issue by vitaliylag** [NodeRedis/node-redis-parser#6]
Buffers are corrupted after sending one more command. Example:

```javascript
var redis  = require('redis'),
    client = redis.createClient({return_buffers: true});

client.set('s1', 'a'.repeat(65527));
client.set('s2', 'b'.repeat(65527));

client.get('s1', function(err, buf) {
	console.log(buf[0]); //prints 97, it's OK

	client.get('s2', function() {
		console.log(buf[0]); //prints 98, but must print 97
	});
});
```

This is starting with javascript parser 2.0.0. The bug occurs when buffer.length >= 65527 (and in 50% cases when buffer.length >= 65517).

Example 2:
```javascript
var redis  = require('redis'),
    client = redis.createClient({return_buffers: true});

client.set('s1', 'a'.repeat(65527));
client.set('s2', 'b'.repeat(65527));

client.get('s1', function(err, buf) {
	setImmediate(function() {
		console.log(buf[0]); //prints 98, but must print 97
	});
});
client.get('s2');
```

In the second example bug occurs only in javascript parser 2.0.1+ (not 2.0.0).

**Comment by BridgeAR** [comment]
This is very bad indeed. With the returnBuffers option we may not use a bufferPool at all. I'm going to fix this in a couple of hours. I'm very sorry that I missed this. I'll fix this tomorrow as I can't find the time right now.
